### ISSUE TITLE
mergeDexRelease FAILED when building Android release app

### ISSUE THREAD

**Issue by thanhvd** [fusetools/react-native-unity2#26]
Hi, I got some issues related to duplicated classes when building Android release app. Can you suggest me a solution to solve it? Thanks.

Error log:
`:app:mergeDexRelease FAILED
ERROR:/Users/abc/Projects/abcx_build/abcXRN_android/unity/android/build/.transforms/d4b3eb04f966925a1fca56c0483736a4/transformed/jetified-unityLibrary-release-runtime/classes.dex: D8: Type org.fmod.FMODAudioDevice is defined multiple times: /Users/abc/Projects/abcx_build/abcXRN_android/unity/android/build/.transforms/d4b3eb04f966925a1fca56c0483736a4/transformed/jetified-unityLibrary-release-runtime/classes.dex, /Users/abc/Projects/abcx_build/abcXRN_android/android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes4.dex
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Type org.fmod.FMODAudioDevice is defined multiple times: /Users/abc/Projects/abcx_build/abcXRN_android/unity/android/build/.transforms/d4b3eb04f966925a1fca56c0483736a4/transformed/jetified-unityLibrary-release-runtime/classes.dex, /Users/abc/Projects/abcx_build/abcXRN_android/android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes4.dex
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:151)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:138)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.merge(DexMergingTask.kt:859)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.run(DexMergingTask.kt:805)
	at com.android.build.gradle.internal.profile.ProfileAwareWorkAction.execute(ProfileAwareWorkAction.kt:74)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:206)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:214)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/abc/Projects/abcx_build/abcXRN_android/unity/android/build/.transforms/d4b3eb04f966925a1fca56c0483736a4/transformed/jetified-unityLibrary-release-runtime/classes.dex
	at Version.fakeStackEntry(Version_3.2.60.java:0)
	at com.android.tools.r8.internal.bi.a(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:68)
	at com.android.tools.r8.internal.bi.a(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:28)
	at com.android.tools.r8.internal.bi.a(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:27)
	at com.android.tools.r8.internal.bi.b(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:3)
	at com.android.tools.r8.D8.run(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:136)
	... 33 more
Caused by: com.android.tools.r8.internal.a: Type org.fmod.FMODAudioDevice is defined multiple times: /Users/abc/Projects/abcx_build/abcXRN_android/unity/android/build/.transforms/d4b3eb04f966925a1fca56c0483736a4/transformed/jetified-unityLibrary-release-runtime/classes.dex, /Users/abc/Projects/abcx_build/abcXRN_android/android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes4.dex
	at com.android.tools.r8.internal.uQ.a(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:14)
	at com.android.tools.r8.internal.uQ.a(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:22)
	at com.android.tools.r8.internal.yK.b(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:7)
	at com.android.tools.r8.internal.yK.a(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:23)
	at com.android.tools.r8.internal.yK.a(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:10)
	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
	at com.android.tools.r8.internal.yK.a(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:6)
	at com.android.tools.r8.graph.A2$a.e(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:4)
	at com.android.tools.r8.dex.b.a(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:105)
	at com.android.tools.r8.dex.b.a(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:28)
	at com.android.tools.r8.D8.a(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:26)
	at com.android.tools.r8.D8.d(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:593)
	at com.android.tools.r8.D8.b(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:1)
	at com.android.tools.r8.internal.bi.a(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:24)
	... 36 more
`

**Comment by mortend** [comment]
I just tried building the [example](https://github.com/fusetools/react-native-unity2/tree/main/example) app as release variant from Android Studio on macOS, and it worked without errors.
<img width="834" alt="image" src="https://github.com/fusetools/react-native-unity2/assets/247798/fa70f3fe-fb83-4622-93da-a0bc595e8500">

* Does the example app work for you?
* Does it work if you `Clean Project` and `Rebuild Project`?

**Comment by thanhvd** [comment]
My issues were resolved. Thanks.
